### ISSUE TITLE
Execute performance test for iotdb with benchmark , but there is an error from the tool .

### ISSUE THREAD

**Issue by bolimocat** [thulab/iotdb-benchmark#109]
Yesterday I tested the  performance of iotdb by benchmark , there is an error info from jdbc interface.
The iotdb release is from https://github.com/apache/incubator-iotdb.git
The iotdb-benchmark release is from https://github.com/thulab/iotdb-benchmark.git

main:
     [copy] Copying 1 file to /home/liurui/lm_test/benchmark/lib
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.826 s
[INFO] Finished at: 2020-01-21T15:32:18+08:00
[INFO] ------------------------------------------------------------------------
/home/liurui/lm_test/benchmark
2020-01-21 15:32:19,150 ERROR cn.edu.tsinghua.iotdb.benchmark.tsdb.iotdb.IoTDB:54 - Initialize IoTDB failed because  
org.apache.iotdb.jdbc.IoTDBSQLException: 
	at org.apache.iotdb.jdbc.IoTDBConnection.getTimeZone(IoTDBConnection.java:479)
	at org.apache.iotdb.jdbc.IoTDBConnection.openSession(IoTDBConnection.java:431)
	at org.apache.iotdb.jdbc.IoTDBConnection.<init>(IoTDBConnection.java:84)
	at org.apache.iotdb.jdbc.IoTDBDriver.connect(IoTDBDriver.java:63)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at cn.edu.tsinghua.iotdb.benchmark.tsdb.iotdb.IoTDB.init(IoTDB.java:51)
	at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper.init(DBWrapper.java:216)
	at cn.edu.tsinghua.iotdb.benchmark.App.testWithDefaultPath(App.java:93)
	at cn.edu.tsinghua.iotdb.benchmark.App.main(App.java:60)

the information is too long to write here complete.

**Comment by liuruiyiyang** [comment]
You may check whether the version of IoTDB is compatible with that of the benchmark. For example, the master branch currently is for IoTDB v0.9.0, please check the pom file of the benchmark branch you are using.
