### ISSUE TITLE
Some error with test

### ISSUE THREAD

**Issue by samuel114** [thulab/iotdb-benchmark#155]
I just want to Data Ingestion Test, 
the iotdb is 0.11.1
it have some error:

root at root in /home/project/iotdb-benchmark-master/iotdb-0.11/target/iotdb-0.11-0.0.1
$ ./benchmark.sh
/home/project/iotdb-benchmark-master/iotdb-0.11/target/iotdb-0.11-0.0.1
2021-02-01 11:05:32,771 INFO  cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper:312 - Registering schema...
2021-02-01 11:05:34,135 INFO  cn.edu.tsinghua.iotdb.benchmark.App:132 - Generating workload buffer...
2021-02-01 11:05:35,983 WARN  org.apache.iotdb.tsfile.common.conf.TSFileDescriptor:90 - Failed to find config file iotdb-engine.properties at classpath, use default configuration
2021-02-01 11:05:36,952 INFO  cn.edu.tsinghua.iotdb.benchmark.client.BaseClient:54 - pool-1-thread-17 0.10% syntheticWorkload is done.
2021-02-01 11:05:36,953 INFO  cn.edu.tsinghua.iotdb.benchmark.client.BaseClient:54 - pool-1-thread-10 0.10% syntheticWorkload is done.
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
2021-02-01 11:05:46,353 ERROR cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper:74 - Insert batch failed because
org.apache.iotdb.rpc.BatchExecutionException: null
        at org.apache.iotdb.rpc.RpcUtils.verifySuccess(RpcUtils.java:59)
        at org.apache.iotdb.rpc.RpcUtils.verifySuccess(RpcUtils.java:48)
        at org.apache.iotdb.session.Session.insertTablet(Session.java:243)
        at org.apache.iotdb.session.Session.insertTablet(Session.java:230)
        at cn.edu.tsinghua.iotdb.benchmark.iotdb011.IoTDBSession.insertOneBatch(IoTDBSession.java:115)
        at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper.insertOneBatch(DBWrapper.java:55)
        at cn.edu.tsinghua.iotdb.benchmark.client.BaseClient.doTest(BaseClient.java:73)
        at cn.edu.tsinghua.iotdb.benchmark.client.Client.run(Client.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fly-chosen** [comment]
what is DB_SWITCH?

**Comment by stormbroken** [comment]
Thanks for your report, but maybe you can provide config.properties for me to find the problem?

**Comment by stormbroken** [comment]
I think you need to provide config.properties or another more details for us to help you, and because there is no response for a long time, I will close this issue. If you need more help, feel free to reopen this issue.
Thanks!
