### ISSUE TITLE
An error happened when I run benchmark.sh

### ISSUE THREAD

**Issue by Tony-ztj** [thulab/iotdb-benchmark#161]
我在本地上下载了iotdb0.11以及iotdb-benchmark，路径如下

calc@calc:~/download/iotdb-benchmark-master$ 
calc@calc:~/download/apache-iotdb-0.11.0$ 

需要的前置软件如maven都下载好了。
在本地路径/download/iotdb-benchmark-master下build

calc@calc:~/download/iotdb-benchmark-master$ mvn clean package -Dmaven.test.skip=true
build项目成功。

按照README.md修改conf后运行benchmark.sh时出错：

calc@calc:~/download/iotdb-benchmark-master$ ./benchmark.sh
/home/calc/download/iotdb-benchmark-master
错误: 找不到或无法加载主类 cn.edu.tsinghua.iotdb.benchmark.App

尝试在benchmark下的iotdb-0.11 内build出错了。
calc@calc:~/download/iotdb-benchmark-master/iotdb-0.11$ mvn clean package -Dmaven.test.skip=true

出现error:
[INFO] Total time:  0.326 s
[INFO] Finished at: 2021-05-05T21:55:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project iotdb-0.11: Could not resolve dependencies for project cn.edu.tsinghua:iotdb-0.11:jar:0.0.1: Failure to find cn.edu.tsinghua:core:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 

未解决该error，在下级目录位置运行benchmark.sh出现error。

calc@calc:~/download/iotdb-benchmark-master/iotdb-0.11/target/iotdb-0.11-0.0.1$ ./benchmark.sh
/home/calc/download/iotdb-benchmark-master/iotdb-0.11/target/iotdb-0.11-0.0.1
2021-05-05 21:57:00,865 ERROR cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper:41 - Failed to get database because 
java.sql.SQLException: didn't support this database
	at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBFactory.getDatabase(DBFactory.java:69)
	at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper.<init>(DBWrapper.java:39)
	at cn.edu.tsinghua.iotdb.benchmark.App.testWithDefaultPath(App.java:95)
	at cn.edu.tsinghua.iotdb.benchmark.App.main(App.java:65)
Exception in thread "main" java.lang.NullPointerException
	at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper.close(DBWrapper.java:301)
	at cn.edu.tsinghua.iotdb.benchmark.App.testWithDefaultPath(App.java:120)
	at cn.edu.tsinghua.iotdb.benchmark.App.main(App.java:65)

**Comment by stormbroken** [comment]
Hello, This error occurs maybe because core module is not package correctly, and benchmark test for iotdb-0.11 need core module.
So maybe you can, rerun mvn clean package -Dmaven.test.skip=true and check whether is ok.
if still not, maybe you can clear local maven cache.
Good luck!
