### ISSUE TITLE
Running against TDengine failed

### ISSUE THREAD

**Issue by ytyou** [thulab/iotdb-benchmark#199]
Running `benchmark.sh` under `tdengine/target/tdengine-0.0.1` results in the following exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:38)
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:126)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at cn.edu.tsinghua.iotdb.benchmark.tdengine.TDengine.init(TDengine.java:73)
        at cn.edu.tsinghua.iotdb.benchmark.tsdb.DBWrapper.init(DBWrapper.java:386)
        at cn.edu.tsinghua.iotdb.benchmark.mode.BaseMode.registerSchema(BaseMode.java:59)
        at cn.edu.tsinghua.iotdb.benchmark.mode.TestWithDefaultPathMode.run(TestWithDefaultPathMode.java:53)
        at cn.edu.tsinghua.iotdb.benchmark.App.main(App.java:61)

```

**Comment by ytyou** [comment]
Never mind, looks like I still need to build TDengine itself, instead of just launching it in a Docker container.
